[connections.default]
warehouse = "QUICKSTART_WH"
role = "ACCOUNTADMIN"
database = "QUICKSTART_COMMON"
schema = "PUBLIC"
account = "ELKXTUP-PK38369"
user = "RINNO"
password = "SnowflakeMetrodata.123"
